version: 2

jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder:0.32

    steps:
      - add_ssh_keys:
          fingerprint: 4f:75:0f:ec:ee:88:c7:1a:d4:5a:d5:53:6e:af:6a:4c

      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "circleci@circleci.com"

      - checkout # check out the code in the project directory

      - run: echo "building the hugo blog"

      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -d docs

      - run: git add docs
      - run: git commit --message "Generated site on $(date) [ci skip]"
      - run: git push origin master
