version: 2

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: jguyomard/hugo-builder:0.32

    steps:
      - git config --global user.name "CircleCI"
      - git config --global user.email "circleci@circleci.com"

      - checkout # check out the code in the project directory

      - run: echo "building the hugo blog"
      
      - docker-compose run hugo -d docs
      - git add docs
      - git commit --message "Generated site on $(date) [ci skip]"
      - git push origin master
